### ISSUE TITLE
P1** Error while creating microApp

### ISSUE THREAD

**Issue by khus29** [pagesource/universal-react-v2#166]
**Describe the bug**
Creation of micro app crashing

**To Reproduce**
Steps to reproduce the behaviour:

1. Create new turbo repo app at root folder
2.  Choose Micro-App option
3. GO with default name
4. Error i terminal

**Expected behaviour**

**terminal output**
What type of app you need? Micro-App
? Enter your app name? header
[02/19/2022 15:09:06PM GMT+0530] - Start creating microApp.
[02/19/2022 15:09:06PM GMT+0530] - Project Created Successfully
(node:22715) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apps' of undefined
    at getNextPort (/Users/khukumar/Documents/projects/universal-react-v2/index.js:77:56)
    at initializeNewProject (/Users/khukumar/Documents/projects/universal-react-v2/index.js:631:56)
    at /Users/khukumar/Documents/projects/universal-react-v2/index.js:1013:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rakeshongithub** [comment]
fixed and closed with new version 0.4.0
