### ISSUE TITLE
Why we removing test command?

### ISSUE THREAD

**Issue by vinodloha** [pagesource/universal-react-v2#188]
Why we removing test command?

_Originally posted by @vinodloha in https://github.com/pagesource/universal-react-v2/pull/187#discussion_r825410104_

**Comment by rakeshongithub** [comment]
@vinodloha Removed for now. Need to do the proper configuration. Right now command not working.

**Comment by rakeshongithub** [comment]
@vinodloha review below PR for adding test command back and configuration to run test cases properly.
PR: https://github.com/pagesource/universal-react-v2/pull/190

**Comment by rakeshongithub** [comment]
test and test:watch command added back with proper config in [v0.11.0](https://github.com/pagesource/universal-react-v2/releases/tag/v0.11.0). Closing.
