### ISSUE TITLE
Testcafe setup not working

### ISSUE THREAD

**Issue by pankajthakur950** [pagesource/universal-react-v2#198]
- Testcafe setup is not working to run the E2E test cases from root package.json. There is no script written to run the test cases from the root package(**Missing Functionality**)

- Testcafe base package.json is deeply nested inside the root package for test cases to run
**To Reproduce**
    1. Create a dummy task in turbo.json file and add script for that task. 
    2. Run the task, turbo setup is not able to locate the testcafe package.json task

- .testcaferc.js file getSrcFile function to find the test source files not able to locate the test files on executing the tasks from root.

- testcafe package.json files misses information like name, version and license which cause issues while running the scripts inside package.json file.

**Comment by rakeshongithub** [comment]
Issue resolved. #200
