### ISSUE TITLE
**P1** : 002 - Update Arch Generator to support following Kind of apps:

### ISSUE THREAD

**Issue by vinodloha** [pagesource/universal-react-v2#53]
1. [x] **SSG**: Next.js based static site generation. 
2. [x] **SSR**: Next.js based server side rendered application. 
3. [x] **Micro App**: Plain React Micro App
4. [ ] ~Initialise a git Repo (Optional)~
5. [x] Way to update existing setup with new features
6. [x] Way to warn user on possible overwrite
7. [x] Way to choose optional features 
8. [x] Copy VSCode Settings to generated App (Optional?)

- The generator will give above 3 options for Arch type question. 
- Update the templates/* directory structure accordingly. 
- Create a templates/common directory to keep common code of each arch type. 
- Ensure generator is able to copy and merge relevant directories while generating new app.

Assignee: Deepanjan

**Comment by deepanjan05** [comment]
"Initialise a git Repo (Optional)" to be created as a seperate P2 Task.
