### ISSUE TITLE
**P1**: 009 - Create a micro-app loader component to consume a Micro App in Next.js Arch.

### ISSUE THREAD

**Issue by vinodloha** [pagesource/universal-react-v2#60]
- [x] Able to Load a micro App based on configuration available in manifest file. 
- [x] Initialise the micro APP. 
- [x] Supply the initial props  
- [x] Force Re-render micro App if props changes. 
- [x] Test this with a Micro App. 

Assignee: Gaurav

**Comment by GodSlayergt** [comment]
created loader without manifest file  [](https://github.com/GodSlayergt/Loader)

**Comment by GodSlayergt** [comment]
created separate script loader hook and made loader more dynamic[https://github.com/GodSlayergt/Loader](url)
